### ISSUE TITLE
file.isSymbolic is not a function

### ISSUE THREAD

**Issue by gynekolog** [phase2/grav-pl-starter#1]
Hi,
i get "file.isSymbolic is not a function" error when run "composer install".

npm log: [2017-12-22T12_58_45_359Z-debug.log](https://github.com/phase2/grav-pl-starter/files/1582583/2017-12-22T12_58_45_359Z-debug.log)
OS: macOS 10.13.3
npm: 5.6.0
node 9.3.0

**Comment by crittermike** [comment]
This seems to be a common issue with Gulp at the moment. https://github.com/gulpjs/gulp/issues/2065

**Comment by gynekolog** [comment]
Error solved in new gulp version.
