### ISSUE TITLE
Fix Install of Twig Namespaces Plugin

### ISSUE THREAD

**Issue by jryanconklin** [phase2/grav-pl-starter#2]
The docs for Twig Namespaces plugin are currently inaccurate. `bin/gpm install twig-namespaces` no longer works for install. It looks like it's pointing to a repo that no longer exists:

https://github.com/chris-clark/grav-plugin-twig-namespaces

We're using this plugin on Particle.

**Comment by crittermike** [comment]
@madhaze you know where that plugin should be pointing to? Obviously `chris-clark` isn't you but I don't see it at https://github.com/madhaze either.

**Comment by jryanconklin** [comment]
Indeed, it'd be great to have an officially working repo for this. Currently I can scrape it off here, but that's not going to be enough to really support this in Particle. 

Happy to help in any way that makes sense.

**Comment by madhaze** [comment]
https://github.com/phase2/grav-pl-starter/commit/bdb0e7851d7704045cb59c696d2a130d2ce03913
@jryanconklin it looks like this was never pulled out to a separate repo.  Just pulled code into a plugin to mirror the functionality that was PL namespaces had (https://github.com/EvanLovely/plugin-twig-namespaces/blob/master/src/PatternLab/TwigNamespaces/PatternLabListener.php#L56)

**Comment by crittermike** [comment]
@jryanconklin so basically it looks like the docs for the twig-namespaces plugin are just wrong, and that there shouldn't be steps in there for installing via `gpm` since the plugin doesn't exist in `gpm`.

What are you trying to do in Particle exactly? You just need that plugin but without the rest of this repo?

**Comment by jryanconklin** [comment]
@mikecrittenden Yeah, just the plugin without the rest of the repo. While it's inconsequential to pull it out and add it to a new Grav, it'd be handy to have it either as a separate repo or in `gpm`. That way Particle README can just point to it.

Else we could probably work out just doing this in the theme file for the Grav version in Particle?

**Comment by crittermike** [comment]
Ok it exists here now: https://github.com/phase2/grav-plugin-twig-namespaces

I'll work on getting it set up in `gpm` on Monday. Thanks for calling this out Ryan!

**Comment by jryanconklin** [comment]
Awesome! Should I roll this issue over to the new repo for `gpm` and close this issue?

**Comment by crittermike** [comment]
Nah, let's leave it here for now. Thanks!

**Comment by crittermike** [comment]
@jryanconklin on second thought, I think we're better off just leaving this as a separate repo for us to use rather than releasing it Grav.org, so I'm going to go ahead and close this issue. Please totally feel free to reopen it if this doesn't solve your use case though.
